name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: dropdown
    id: work-on-fix
    attributes:
      label: Would you like to work on a fix?
      description: Let us know if you're interested in contributing a fix
      options:
        - "Yes"
        - "No"
      default: 1
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure you are able to reproduce the bug in the main branch, too.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or provide links...

  - type: input
    id: os
    attributes:
      label: OS
      description: Your operating system
      placeholder: e.g. Ubuntu 20.04, Windows 11, macOS 13.0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "prs-rs version"
      description: The version of prs-rs you're using
      placeholder: e.g. 0.1.0
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
