site_name: Prs-rs Docs
site_url: https://github.com/Sewer56/prs-rs

repo_name: Sewer56/prs-rs
repo_url: https://github.com/Sewer56/prs-rs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56
    # - icon: fontawesome/brands/twitter
    #  link: https://twitter.com/thesewer56?lang=en-GB

extra_css:
  - vendor/Reloaded/Stylesheets/reloaded.css

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded3-slate
  features:
    - navigation.instant

plugins:
  - offline
  - search
  - exclude-unused-files:
      file_types_to_check: ["psd", "7z", "kra", "avif"]
      file_types_override_mode: append
      enabled: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

nav:
  - Home: index.md
  - Contributing: contributing.md
  - License: license.md
  - How to Document: https://github.com/Reloaded-Project/Reloaded.MkDocsMaterial.Themes.R2/blob/master/docs/Pages/contributing.md
