name: Auto Changelog

on:
  push:
    tags:
      - '*'

jobs:
  generate_and_upload_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate and Upload Changelog
        id: changelog
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/upload-changelog@v1 
        with:
          is-release: ${{ startsWith(github.ref, 'refs/tags/') }}
          release-tag: ${{ github.ref_name }}
          changelog-template: "changelog.hbs"
