name: Auto Changelog

on:
  push:
    tags:
      - '*'

jobs:
  generate_and_upload_changelog:
    runs-on: ubuntu-latest 
    permissions: 
      contents: write

    steps:
      - name: Generate changelog
        uses: Reloaded-Project/devops-changelog@v1
        with:
          output: CHANGELOG.md
          upload-artifact: true
          upload-release: true
          override-starting-version: true
          is-release: ${{ startsWith(github.ref, 'refs/tags/') }}
          release-tag: ${{ github.ref_name }}