name: Test, Upload Coverage and Release Rust

on:
  push:
    branches: [ main, pgo, csharp-bindings, cli ]
    tags:
      - '*'
  pull_request:
    branches: [ main, pgo, csharp-bindings, cli ]
  workflow_dispatch:

jobs:
  test-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - id: test-rust
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/test-and-coverage@v1 # upgrade if needed
        with:
          rust_branch: 'nightly'

  build-c-libs:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_pgo: true
            use_cross: false
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use_pgo: true
            use_cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_pgo: false # no native runner
            use_cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            use_pgo: false # no native runner
            use_cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_pgo: true
            use_cross: false
          - os: windows-latest
            target: i686-pc-windows-msvc
            use_pgo: true
            use_cross: false
          - os: windows-latest 
            target: aarch64-pc-windows-msvc
            use_pgo: false # no native runner
            use_cross: false
          - os: macos-13 # x86
            target: x86_64-apple-darwin
            use_pgo: true
            use_cross: false
          - os: macos-14 # M1
            target: aarch64-apple-darwin
            use_pgo: true
            use_cross: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - id: build-libs
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/build-c-library@v1 # upgrade if needed
        with:
          target: ${{ matrix.target }}
          use_pgo: ${{ matrix.use_pgo }}
          use_cross: ${{ matrix.use_cross }}
          features: "c-exports"

  build-cli-tool:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_pgo: true
            use_cross: false
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use_pgo: true
            use_cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_pgo: false # no native runner
            use_cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            use_pgo: false # no native runner
            use_cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use_pgo: true
            use_cross: false
          - os: windows-latest
            target: i686-pc-windows-msvc
            use_pgo: true
            use_cross: false
          - os: windows-latest 
            target: aarch64-pc-windows-msvc
            use_pgo: false # no native runner
            use_cross: false
          - os: macos-13 # x86
            target: x86_64-apple-darwin
            use_pgo: true
            use_cross: false
          - os: macos-14 # M1
            target: aarch64-apple-darwin
            use_pgo: true
            use_cross: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - id: build-libs
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/build-lightweight-binary@v1 # upgrade if needed
        with:
          target: ${{ matrix.target }}
          use_pgo: ${{ matrix.use_pgo }}
          use_cross: ${{ matrix.use_cross }}
          rust_project_path: "tools/cli/"
          crate_name: "prs-rs-cli"

  build-c-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate C++ bindings
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/generate-bindings@v1
        with:
          config_file: cbindgen_cpp.toml
          header_file: bindings_cpp.hpp
  
      - name: Generate C bindings
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/generate-bindings@v1
        with:
          config_file: cbindgen_c.toml
          header_file: bindings_c.h

  build-dotnet-library:
    needs: build-c-libs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Package .NET Library
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/build-dotnet-library@dotnet-bindings
        with:
          targets: 'x86_64-unknown-linux-gnu,i686-unknown-linux-gnu,aarch64-unknown-linux-gnu,armv7-unknown-linux-gnueabihf,x86_64-pc-windows-msvc,i686-pc-windows-msvc,aarch64-pc-windows-msvc,x86_64-apple-darwin,aarch64-apple-darwin'

  publish-crate:
    permissions:
      contents: write

    needs: [test-native,build-c-libs,build-c-headers,build-dotnet-library]
    # Publish only on tags
    if: startsWith(github.ref, 'refs/tags/') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ↙️ Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload to NuGet
        shell: pwsh
        run: |
          $items = Get-ChildItem -Path "artifacts/**.nupkg" -Recurse
          Foreach ($item in $items)
          {
              Write-Host "Pushing $item"
              dotnet nuget push "$item" -k "${{ secrets.NUGET_KEY }}" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
          }

          $items = Get-ChildItem -Path "artifacts/**.snupkg" -Recurse
          Foreach ($item in $items)
          {
              Write-Host "Pushing Symbol Package $item"
              dotnet nuget push "$item" -k "${{ secrets.NUGET_KEY }}" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
          }

      - name: Compress Artifacts
        shell: bash
        run: |
          dir="artifacts"
          if [ ! -d "$dir" ]; then
            echo "Directory $dir does not exist. No artifacts found."
            exit 0
          fi

          for subdir in "$dir"/*; do
            if [ -d "$subdir" ]; then
              base=$(basename "$subdir")
              zip -r "$dir/$base.zip" "$subdir"
              rm -r "$subdir"
            fi
          done
          ls -A ./artifacts

      - name: GitHub Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*

      - name: Publish to crates.io
        uses: Reloaded-Project/reloaded-project-configurations-rust/.github/actions/publish-crate@v1
        with:
          token: ${{ secrets.CRATES_IO_TOKEN }}